name: 'Self Test'
on:
  pull_request:
  push:
    branches:
      - 'feature/*'
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bc-lee/newline-eof-action@master
      - uses: ./
